Update jenkinsfile to run smoketest
secure-device-onboard/pri pull request #13
Opened 2020-07-20 10:35 UTC by dmareddx

Added a new stage to run smoke test on pri binaries with other SDO components.
 
Signed-off-by: Mareddy, Deepthi <depthix.mareddy@intel.com>

2020-07-20 12:36 UTC, trbehera requested changes

2020-07-20 12:36 UTC, trbehera commented on Jenkinsfile.yml
> +
Whitespace, please remove.

2020-07-20 13:50 UTC, dmareddx commented on Jenkinsfile.yml
> +
whitespace has been removed

2020-07-21 14:28 UTC, trbehera commented
@dmareddx Please squash all changes to a single commit and repost.

2020-07-22 10:05 UTC, trbehera approved these changes

2020-07-22 15:37 UTC, prateekcr approved these changes

2020-07-23 05:24 UTC, merged